nelmio_api_doc:
    documentation:
        info:
            title: Thesis
            description: This is backend app is for storing blocks, sequences, and modifications.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/rest
