name: Test App
on: [push, pull_request]
jobs:
  build:
    name: Symfony (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:8.0
        MYSQL_ROOT_PASSWORD: qHTavO1ajSOnQzUdi3ef
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql
          coverage: xdebug #optional
      
      - name: Start mysql service
        run: sudo /etc/init.d/mysql start
      
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      
      - name: Validate composer.json and composer.lock
      run: composer validate
      
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      
      - name: Install Composer dependencies
        run: |
          composer require --dev symfony/orm-pack symfony/phpunit-bridge
          composer install --no-progress --prefer-dist --optimize-autoloader
          php bin/phpunit install
      
      - name: Run Migration
        run: |
          php bin/console doctrine:database:create -n
          php bin/console doctrine:mig:mig -n
          php bin/console doctrine:fixtures:load -n
        env:
          DATABASE_URL: mysql2://root:qHTavO1ajSOnQzUdi3ef@127.0.0.1:3306/msb?serverVersion=8.0
      
      - name: Run Tests
        run: php bin/phpunit --coverage-text
